class Financials {
  constructor() {

    this.totalRevenue = new Array(100).fill(new Array(9).fill(0)) // this is a 2D array where each row represents time (10000 ticks) and each column represents a train (up to 9 trains). The value at [i][j] represents the revenue generated by train j at time i. This allows us to track the revenue generated by each train over time and calculate the total revenue at any given time by summing the values in the corresponding row.
    this.totalExpenses = new Array(100).fill(new Array(9).fill(0)) // this is a 2D array where each row represents time (10000 ticks) and each column represents a train (up to 9 trains). The value at [i][j] represents the revenue generated by train j at time i. This allows us to track the revenue generated by each train over time and calculate the total revenue at any given time by summing the values in the corresponding row.
    this.profit = new Array(100).fill(new Array(9).fill(0)) // this is a 2D array where each row represents time (10000 ticks) and each column represents a train (up to 9 trains). The value at [i][j] represents the revenue generated by train j at time i. This allows us to track the revenue generated by each train over time and calculate the total revenue at any given time by summing the values in the corresponding row.

    this.engineCost = 1000000
    this.coachCost = 500000
    this.collisionCost = 20000000 
    this.trackCostPerUnit = 1000

    this.revenuePerUnitDistancePerCoach = 5
    this.ticksPerTimeUnit = 10000
  }
  incrementRevenue(timeIndex, trainIndex, amount) {
    this.totalRevenue[timeIndex][trainIndex] += amount
    this.updateProfit(timeIndex, trainIndex)
  }
  incrementExpenses(timeIndex, trainIndex, amount) {
    this.totalExpenses[timeIndex][trainIndex] += amount
    this.updateProfit(timeIndex, trainIndex)
  }
  updateProfit(timeIndex, trainIndex) {
    this.profit[timeIndex][trainIndex] = this.totalRevenue[timeIndex][trainIndex] - this.totalExpenses[timeIndex][trainIndex]
  }

  //this is called externally and hence we use ticks to call it
  getFinancialSummary(ticks) {
    const timeIndex = Math.floor(ticks / this.ticksPerTimeUnit)
    const totalRevenue = this.totalRevenue[timeIndex].reduce((a, b) => a + b, 0)
    const totalExpenses = this.totalExpenses[timeIndex].reduce((a, b) => a + b, 0)
    const profit = this.profit[timeIndex].reduce((a, b) => a + b, 0)

    return {
      totalRevenue,
      totalExpenses,
      profit
    }
  }

  getFinancialSummaryByTrain(ticks) {
    const timeIndex = Math.floor(ticks / this.ticksPerTimeUnit)
    const totalRevenue = this.totalRevenue[timeIndex]
    const totalExpenses = this.totalExpenses[timeIndex]
    const profit = this.profit[timeIndex]
    return {
      totalRevenue,
      totalExpenses,
      profit
    }
  }

  //this is called externally and hence we use ticks, trainNumber to call it
  buyCoach(ticks,trainNumber,numCoaches) {
    const trainIndex = trainNumber - 1
    const timeIndex = Math.floor(ticks / this.ticksPerTimeUnit)
    const cost = this.coachCost * numCoaches
    this.incrementExpenses(timeIndex,trainIndex,cost)
    return cost
  }

  //this is called externally and hence we use ticks, trainNumber to call it
  buyEngine(ticks,trainNumber) {
    const trainIndex = trainNumber - 1
    const timeIndex = Math.floor(ticks / this.ticksPerTimeUnit)
    this.incrementExpenses(timeIndex,trainIndex,this.engineCost)
    return this.engineCost
  }
  
  //this is called externally and hence we use ticks, trainNumber to call it
  incrementTrackCost(ticks,trainNumber,distance) {
    const trainIndex = trainNumber - 1
    const timeIndex = Math.floor(ticks / this.ticksPerTimeUnit)
    const cost = this.trackCostPerUnit * distance
    this.incrementExpenses(timeIndex,trainIndex,cost)
    return cost
  }
  
  //this is called externally and hence we use ticks, trainNumber to call it
  incrementRevenueFromOperations(ticks, trainNumber, distance, numCoaches) {
    const trainIndex = trainNumber - 1
    const timeIndex = Math.floor(ticks / this.ticksPerTimeUnit)
    const revenue = this.revenuePerUnitDistancePerCoach * distance * numCoaches
    this.incrementRevenue(timeIndex, trainIndex, revenue)
    return revenue
  }

  //this is called externally and hence we use ticks, trainNumber to call it
  incrementCollisionCost(ticks, trainNumber1, trainNumber2) {
    const trainIndex1 = trainNumber1 - 1
    const trainIndex2 = trainNumber2 - 1
    const timeIndex = Math.floor(ticks / this.ticksPerTimeUnit)
    this.incrementExpenses(timeIndex, trainIndex1, this.collisionCost/2)
    this.incrementExpenses(timeIndex, trainIndex2, this.collisionCost/2)
    return this.collisionCost
  }
}
export const financials = new Financials()