"use strict";
import { audioManager } from './audioManager.js'
// createAudioManager(audioSources, options) returns an object with play, pause, stop, and other audio control methods.
// it already has 2 sounds, beep and train
class Train {
  static lengthEngine = 40
  static widthEngine = 14
  static lengthCoach = 20
  static widthCoach = 12
  static chimney_r = 30
  static maxSmokePuffs = 60
  static smokeColor = `#222`
  static coachColor = `#00ff00`
  static intersectionDist = 10
  static maxNumCoaches = 15
  static maxNumFreightWagons = 100
  static minNumCoaches = 2
  static coachPassengerCapacity = 100
  static baseTicketPrice = 400
  static rawMaterialCapacityPerFreightCoach = 10000 // fixed raw material capacity per freight coach to keep it simple. We can adjust this as needed to make it more realistic.
  static rawMaterialChargePerUnit = 100 // fixed charge per unit of raw material to keep it simple. Revenue is calculated based on the amount of raw material unloaded at the station.
  static ticketPriceMap = new Map() // key is from row,col to row,col and value is the ticket price for that route. 
  // We populate this as we go unless the ticket price is already in the map. 
  

  constructor({
    ctx,
    ctxTemp,
    track,
    color,
    numCoaches,
    trainName,
    delayBeforeStart = 1,
    trainNumber,
    intersections,
    financials,
    travelPopulation,
    rawMaterialDemand,
    rawMaterialSupply,
    getCurrentTimeIndex,
    trainType = 'passenger',
    lane = 0,
    visualLengthScale = 1,
    maxVisualCoaches,
    popups,
    trainInfo
  } = {}) {
    this.ctx = ctx
    this.ctxTemp = ctxTemp
    this.track = track
    this.color = color
    this.trainType = trainType
    // speed parameter: 1=slowest, 20=fastest. Internally inverted to a frame-step divisor (lower=faster).
    // Freight trains run at a fixed half-of-maximum speed (divisor 11 = parameter 10 out of 20).
    const maxInitialCoaches = this.trainType === 'freight' ? Train.maxNumFreightWagons : Train.maxNumCoaches
    this.numCoaches = numCoaches ? Math.min(Math.max(numCoaches, Train.minNumCoaches), maxInitialCoaches) : Math.floor((Train.minNumCoaches + Train.maxNumCoaches) / 2)
    this.ticks = 0
    this.count = 0
    this.isReturning = false
    this.trainName = trainName
    this.trainNumber = trainNumber
    this.visualLengthScale = Math.max(0.2, Math.min(1, visualLengthScale))
    this.hasExplicitVisualCoachCap = maxVisualCoaches != null
    this.maxVisualCoaches = Math.max(1, this.hasExplicitVisualCoachCap ? maxVisualCoaches : this.numCoaches)
    this.paused = false
    this.userPaused = false
    this.dwellPaused = false
    this.delayBeforeStart = delayBeforeStart
    this.intersections = intersections
    this.activeIntersections = new Map()
    this.lane = Number.isFinite(lane) ? lane : 0
    this.trainlength = Train.lengthEngine + (Train.lengthCoach + 2) * this.numCoaches
    this.financials = financials
    this.getCurrentTimeIndex = getCurrentTimeIndex
    this.dysfunctional = false
    this.repairTime = 5000 //time in ticks for which the train will be dysfunctional after a collision. This is to simulate the time taken for the train to be repaired after a collision.
    this.repairticks = 0
    // we need stations here to calculate the number of passengers traveling from one station to another station on the route of the train. This is used to calculate the revenue generated by the train operations based on the number of passengers on board and the distance traveled.
    // and also to stop at each station for a certain amount of time.
    this.stations = track.getStations()
    // key is the from station and to station coordinates and value is the number of passengers going on that route. For example, 
    // if there are 10 passengers going from station A to station B, then the key will be "Ax,Ay-Bx,By" and the value will be 10. This is used to calculate the revenue generated by the train operations based on the number of passengers on board and the distance traveled.
    // this is to be populated when the station is added. Let us say that we wanto calculate
    // the number of passengers traveling from station A to station B, 
    // let us say that travelPopulation for A is TA and travelPopulation for B is TB
    // then number is TA*TB/TT where TT is the total travel population.
    // When the train starts at the Starting point it takes in passengers for all the
    // stations on the route. When the train reaches the first station on route, it unloads the
    // passengers for that station and takes on the passengers for all the following stations and so on.
    // In our data model, station is part of the track and hence we will need to access the station information 
    // from the track to get the coordinates of the station and then use that to get the travel population for that 
    // station to calculate the number of passengers traveling from that station to all the following stations on the route. 
    // This is a simplification but it should work for our purposes.
    this.passengerMap = new Map()
    this.travelPopulation = travelPopulation
    this.totalTravelPopulation = Array.from(this.travelPopulation.travelPopulation.values()).reduce((a, b) => a + b.population, 0)
    this.passengersOnBoard = 0
    this.lastProcessedStationNumber = null  // prevents boarding/deboarding from firing on every frame while at a station
    this.stationVisitContext = null
    this.remainingDwellTime = 0
    this.freightTrainDwellTime = 200 // fixed dwell time for freight trains at each station for loading and unloading. This can be adjusted as needed.
    this.rawMaterialDemand = rawMaterialDemand
    this.rawMaterialSupply = rawMaterialSupply
    this.rawMaterialOnBoard = 0
    this.distanceTraveledInTimeUnit = 0
    this.popups = popups
    if (!trainInfo) {
      throw new Error('TrainInfo instance required')
    }
    this.trainInfo = trainInfo
    this.tripNumber = 1
    //when freight train has an upgraded engine, its max speed increases by 50%
    //when passenger train has an upgraded engine, its speed increases quickly from zero
    this.speed = this.trainType == 'passenger' ? 1 : 11
    this.upgradedEngine = false
    this.debugLaneLogged = false
    this.parallelSegmentCells = this.buildParallelSegmentCellSet()
    this.awaitingTurnaround = false
    this.smokePuffs = []
    this.lastSmokeEmitTick = 0
    this.smokeSetting = 'high'

    
    this.updateUI()
    
  }

  normalizeSmokeSetting(level) {
    const value = typeof level === 'string' ? level.toLowerCase() : 'high'
    if (value === 'off' || value === 'low' || value === 'high') {
      return value
    }
    return 'high'
  }

  setSmokeSetting(level) {
    this.smokeSetting = this.normalizeSmokeSetting(level)
    if (this.smokeSetting === 'off') {
      this.smokePuffs.length = 0
    }
    return this.smokeSetting
  }

  buildParallelSegmentCellSet() {
    const cells = new Set()
    if (!this.track?.overlapMatches?.length) {
      return cells
    }

    const stepSize = Number.isFinite(this.intersections?.gridSize) && this.intersections.gridSize > 0
      ? this.intersections.gridSize
      : 1

    this.track.overlapMatches.forEach((match) => {
      if (!(match?.commonSegmentsMap instanceof Map)) {
        return
      }
      match.commonSegmentsMap.forEach((segment) => {
        if (!segment) {
          return
        }
        const dx = segment.endx - segment.startx
        const dy = segment.endy - segment.starty
        const maxAxisDistance = Math.max(Math.abs(dx), Math.abs(dy))
        const steps = Math.max(1, Math.round(maxAxisDistance / stepSize))

        for (let i = 0; i <= steps; i++) {
          const t = i / steps
          const px = segment.startx + dx * t
          const py = segment.starty + dy * t
          const cell = this.intersections.getCellFromCanvasPoint(px, py)
          if (!cell) {
            continue
          }
          cells.add(`${cell.row},${cell.col}`)
        }
      })
    })

    return cells
  }

  isOnParallelSegment(x, y) {
    if (!this.parallelSegmentCells || this.parallelSegmentCells.size === 0) {
      return false
    }
    const cell = this.intersections.getCellFromCanvasPoint(x, y)
    if (!cell) {
      return false
    }
    return this.parallelSegmentCells.has(`${cell.row},${cell.col}`)
  }
  
  updateUI() {
    const newCountEl = document.querySelector(`#newCount${this.trainNumber}`)
    if (!newCountEl) return
    newCountEl.value = this.numCoaches
    newCountEl.setAttribute("min", Train.minNumCoaches);
    newCountEl.setAttribute("max", this.trainType === "freight" ? Train.maxNumFreightWagons : Train.maxNumCoaches);

    // Add train label in info widget once.
    const infoContainer = document.querySelector('#infoForTrain')
    if (infoContainer && !infoContainer.querySelector(`span[data-value="${this.trainNumber}"]`)) {
      const infoSpan = document.createElement('span')
      infoSpan.dataset.value = String(this.trainNumber)
      infoSpan.textContent = `T${this.trainNumber}`
      infoSpan.style = 'background-color:' + (this.trainType === 'freight' ? 'rgba(80,80,80,0.75)' : this.color) + ';cursor:pointer;font-size:1.0em;padding:2px;margin:1px;border:1px solid black;display:inline-block'
      infoContainer.appendChild(infoSpan)
    }

    // Add train label in station widget once; click behavior is delegated in script.js.
    const stationContainer = document.querySelector('#stationFortrain')
    if (stationContainer && !stationContainer.querySelector(`span[data-value="${this.trainNumber}"]`)) {
      const stationSpan = document.createElement('span')
      stationSpan.dataset.value = String(this.trainNumber)
      stationSpan.dataset.role = 'station-train'
      stationSpan.textContent = `T${this.trainNumber}`
      stationSpan.style = 'background-color:' + (this.trainType === 'freight' ? 'rgba(80,80,80,0.75)' : this.color) + ';cursor:pointer;font-size:1.0em;padding:2px;margin:1px;border:1px solid black;display:inline-block'
      stationContainer.appendChild(stationSpan)
    }
  }
  
  upgradeEngine() {
    if (this.upgradedEngine) return // already upgraded
    this.financials.upgradeEngine(this.getCurrentTimeIndex(), this.trainNumber)
    this.upgradedEngine = true
    if (this.trainType === 'freight') {
      this.speed = 5
    }
  }

  addCoach(numCoaches = 1) {

    console.log(`Adding ${numCoaches} coaches to train ${this.trainNumber}`)
    const maxAllowedCoaches = this.trainType === "freight" ? Train.maxNumFreightWagons : Train.maxNumCoaches
    if (this.numCoaches+numCoaches > maxAllowedCoaches) return

    this.numCoaches += numCoaches
    if (!this.hasExplicitVisualCoachCap) {
      this.maxVisualCoaches = this.numCoaches
    }
    this.trainlength = Train.lengthEngine + (Train.lengthCoach + 2) * this.numCoaches
    // update the num coaches label in the UI
    // const newCountEl = document.querySelector(`#newCount${this.trainNumber}`)
    // if (newCountEl) {
    //   newCountEl.value = this.numCoaches
    // }
  }
  removeCoach(numCoaches = 1) {

    console.log(`Removing ${numCoaches} coaches from train ${this.trainNumber}`)
    
    if (this.numCoaches <= Train.minNumCoaches) return
    if (numCoaches <= 0) return

    if ((this.numCoaches - numCoaches) >= Train.minNumCoaches) {
      this.numCoaches -= numCoaches
      if (!this.hasExplicitVisualCoachCap) {
        this.maxVisualCoaches = this.numCoaches
      }
      this.trainlength = Train.lengthEngine + (Train.lengthCoach + 2) * this.numCoaches
      // update the num coaches label in the UI
      const newCountEl = document.querySelector(`#newCount${this.trainNumber}`)
      if (newCountEl) {
        newCountEl.value = this.numCoaches
      }
    }
  }

  setDysfunctional(state) {
    this.dysfunctional = state
    if (state) {
      this.awaitingTurnaround = false
      this.activeIntersections.forEach((intersection, key) => {
        this.clearIntersection(intersection.row, intersection.col)
        this.intersections.updateIntersection(intersection.row, intersection.col, null, this.lane)
      })
    } else {
      //repair is done, reset the repair ticks and allow the train to move again
      this.repairticks = 0
      //also after the train is repaired
      //set the train to its original position
      this.count = 0
      this.isReturning = false
      this.paused = false
      this.userPaused = false
      this.awaitingTurnaround = false
    }
  }

  startStop() {
    this.userPaused = !this.userPaused
  }

  setUserPaused(state) {
    this.userPaused = !!state
  }

  setLane(lane) {
    const nextLane = Number.isFinite(lane) ? lane : this.lane
    if (nextLane === this.lane) return

    this.activeIntersections.forEach((intersection) => {
      this.intersections.updateIntersection(intersection.row, intersection.col, null, this.lane)
    })
    this.lane = nextLane
    this.activeIntersections.forEach((intersection) => {
      this.intersections.updateIntersection(intersection.row, intersection.col, this.trainNumber, this.lane)
    })
  }

  draw() {

    // we want to start the train gradually from a zero speed to avoid the jarring effect of the train suddenly appearing at full speed. So we can use the ticks variable to control the speed of the train in the initial phase. The train will start moving after a certain number of ticks have passed, which is determined by the delayBeforeStart variable. We can also use the ticks variable to control the speed of the train in the initial phase. The train will start moving after a certain number of ticks have passed, which is determined by the delayBeforeStart variable. This way we can create a smooth acceleration effect for the train when it starts moving.
    let currSpeed
    if (!this.upgradedEngine) {

      const step1 = this.trainType == "passenger" ? 20 - Math.floor(this.speed * 1 / 6) : 20
      const step2 = this.trainType == "passenger" ? 20 - Math.floor(this.speed * 2 / 6) : 20
      const step3 = this.trainType == "passenger" ? 20 - Math.floor(this.speed * 3 / 6) : 20
      const step4 = this.trainType == "passenger" ? 20 - Math.floor(this.speed * 4 / 6) : 20
      const step5 = this.trainType == "passenger" ? 20 - Math.floor(this.speed * 5 / 6) : 20

      currSpeed = this.ticks < 50 ? step1 : this.ticks < 150 ? step2 : this.ticks < 250 ? step3 : this.ticks < 350 ?
        step4 : this.ticks < 450 ? step5 : this.speed
    } else {
      const step1 = this.trainType == "freight" ? 20 - Math.floor(this.speed * 1 / 6) : 20
      const step2 = this.trainType == "freight" ? 20 - Math.floor(this.speed * 2 / 6) : 20
      const step3 = this.trainType == "freight" ? 20 - Math.floor(this.speed * 3 / 6) : 20
      currSpeed = this.ticks < 50 ? step1 : this.ticks < 150 ? step2 : this.ticks < 250 ? step3 : this.speed
    }

    if (this.dysfunctional) {
      // If the train is dysfunctional, we don't update its position or draw it.
      // till a certain time has passed which is the time needed for th train 
      // to be repaired.
      const healthBar = document.querySelector(`#health${this.trainNumber}`)
      if (this.repairticks % 1000 == 0) {
        //increase the width of the health bar to indicate the progress of the repair
        if (healthBar) {
          const width = (this.repairticks / this.repairTime) * 30
          healthBar.style.width = `${width}px`
        }
      }
      this.repairticks++
      if (this.repairticks >= this.repairTime) {
        this.setDysfunctional(false)
        if (healthBar) {
          healthBar.style.width = `30px`
        }
      }
      return
    }



    //draw is called on each frame from the game loop
    const d = 4 //distance between one coach and the next

    // Only increment ticks and dwell time when game is not paused
    if (!this.userPaused) {
      this.ticks++
      this.remainingDwellTime--
    }

    //train is not drawn till this.ticks reach a certain level
    if (this.ticks < this.delayBeforeStart * 100) return

    //Also we do not draw the train unless the whole train has reached the starting point. 
    //This is to avoid the train appearing to be cut off at the beginning of the track
    // if (segment && segment.startDistance < this.trainlength) return

    // we have to set the position of the engine based on 
    // how far it has moved on the tracks
    this.dwellPaused = this.remainingDwellTime > 0 ? true : false

    if ((this.ticks % currSpeed == 0) && !this.userPaused && !this.dwellPaused) {
      //this controls the overall speed of the train. The lower the engineSpeed, the faster the train moves. The train moves one step after every engineSpeed number of frames
      const previousCount = this.count
      const distanceStep = 3
      const nextCount = this.count + distanceStep
      let distanceMoved = distanceStep
      if (this.track.totalLength > 0 && nextCount >= this.track.totalLength) {
        distanceMoved = Math.max(0, this.track.totalLength - previousCount)
        this.count = this.track.totalLength
        this.awaitingTurnaround = true
      } else {
        this.count = nextCount
      }
      this.distanceTraveledInTimeUnit += distanceMoved
    }

    let { x, y, direction, segment } = this.getPosition(0)
    //location is saved in the train object 
    this.x = x
    this.y = y
    // this.ctx.fillText(`T${this.trainNumber}`, x - 10, y - 10)

    // this section for calculating the number of passengers
    // boarding and alighting at each station and the revenue generated by the train operations based on the number of passengers on board and the distance traveled. We assume that all passengers get on the train at the starting point and get off at their destination station. This is a simplification but it should work for our purposes.
    let atAStation = false
    const stationNumbers = this.stations.map(st => st.stationNumber)
    const minStationNumber = stationNumbers.length ? Math.min(...stationNumbers) : 0
    const maxStationNumber = stationNumbers.length ? Math.max(...stationNumbers) : 0
    for (const station of this.stations) {
      const isAtStation = (Math.abs(x - station.x) < 5) && (Math.abs(y - station.y) < 5)
      if (!isAtStation) continue

      const isTerminalForCurrentDirection = (!this.isReturning && station.stationNumber === maxStationNumber) || (this.isReturning && station.stationNumber === minStationNumber)
      const trainIsReturning = isTerminalForCurrentDirection ? !this.isReturning : this.isReturning
      if (this.trainType == 'passenger') {
        //reached a station. Set the dwell time
        let totalDeboarding = 0
        let totalBoarding = 0
        const thisStationKey = `${station.stationNumber}`
        atAStation = true
        if (this.lastProcessedStationNumber === station.stationNumber) continue  // already processed this visit, skip
        this.lastProcessedStationNumber = station.stationNumber
        this.remainingDwellTime = station.stationNumber != minStationNumber && station.stationNumber != maxStationNumber ? station.dwellTime : 0
        //deboarding loop
        // for (const station of this.stations) {
        for (const fromToKey of this.passengerMap.keys()) {
          const [fromKey, toKeyInMap] = fromToKey.split('-')
          if (toKeyInMap === thisStationKey) {
            totalDeboarding += this.passengerMap.get(fromToKey)
            this.passengerMap.set(fromToKey, 0) // all passengers for that route get off at the destination station or we can delete this key
          }
        }
        // }
        //boarding loop
        // Here we calculate the number of passengers boarding the train at this station for all the following 
        // stations on the route. We can get the travel population for this station and then calculate the number 
        // of passengers boarding for each of the following stations on the route based on the travel population 
        // for those stations and the total travel population. This is a simplification but it should work for our purposes.


        const travelPopFrom = this.travelPopulation.travelPopulation.get(`${station.x},${station.y}`)?.population ?? 0
        for (const nextStation of this.stations) {
          if (!trainIsReturning && (nextStation.stationNumber > station.stationNumber) || trainIsReturning && (nextStation.stationNumber < station.stationNumber)) {
            // if (this.isReturning) debugger
            const toKey = `${nextStation.stationNumber}`
            const travelPopTo = this.travelPopulation.travelPopulation.get(`${nextStation.x},${nextStation.y}`)?.population ?? 0
            //add randomness of +- 30% to the number of passengers boarding to make it more realistic and to avoid having the same number of passengers boarding at each station for the same travel population numbers. This is because in reality, the number of passengers boarding at a station can vary even if the travel population is the same due to various factors such as time of day, day of week, special events, etc. This will add some variability to our simulation and make it more interesting.
            let boarding = Math.ceil(travelPopTo * travelPopFrom * (0.7 + 0.6 * Math.random()) / this.totalTravelPopulation)
            totalBoarding += boarding
            const routeKey = `${thisStationKey}-${toKey}`
            this.passengerMap.set(routeKey, boarding)
          }
        }

        const passengerCapacity = this.numCoaches * Train.coachPassengerCapacity
        //we fix the map only if the number of passengers trying to board the train exceeds the passenger capacity of the train. This is to avoid the situation where we have a large number of passengers trying to board the train and we end up with a negative number of passengers on board after deboarding.
        let proportionBoarding = 1
        let unableToBoard = 0
        if (totalBoarding + this.passengersOnBoard - totalDeboarding > passengerCapacity) {
          // if the number of passengers on board after boarding and deboarding exceeds the passenger capacity of the train, then we can assume that only the passengers that can fit in the train will board the train and the rest will not board the train. This is a simplification but it should work for our purposes.
          unableToBoard = totalBoarding + this.passengersOnBoard - totalDeboarding - passengerCapacity
          // proportionBoarding = (passengerCapacity - this.passengersOnBoard + totalDeboarding) / totalBoarding
          proportionBoarding = (totalBoarding - unableToBoard) / totalBoarding
        }
        totalBoarding = Math.floor(totalBoarding * proportionBoarding)
        let ticketPrice = 0
        let adjustedBoarding = 0
        let totalAdjustedBoarding = 0
        let earnings = 0
        let totalEarnings = 0
        for (const fromToKey of this.passengerMap.keys()) {
          const [fromKey, toKeyInMap] = fromToKey.split('-')
          if (fromKey === thisStationKey) {
            const currentBoarding = this.passengerMap.get(fromToKey)
            adjustedBoarding = Math.floor(currentBoarding * proportionBoarding)
            totalAdjustedBoarding += adjustedBoarding
            const toStationObj = this.stations.find(st => st.stationNumber === parseInt(toKeyInMap))
            const ticketPriceKey1 = `${Math.floor(station.x / 100) + 1},${Math.floor(station.y / 100) + 1}-${Math.floor(toStationObj.x / 100) + 1},${Math.floor(toStationObj.y / 100) + 1}`
            const ticketPriceKey2 = `${Math.floor(toStationObj.x / 100) + 1},${Math.floor(toStationObj.y / 100) + 1}-${Math.floor(station.x / 100) + 1},${Math.floor(station.y / 100) + 1}`
            // following to save ticket price caclulation time on subsequent lookups for the same route. 
            // console.log(`totalBoarding: ${totalBoarding}, proportionalBoarding: ${proportionBoarding}, adjustedBoarding: ${adjustedBoarding}, ticketPriceKey1: ${ticketPriceKey1}, ticketPriceKey2: ${ticketPriceKey2}`)
            if (Train.ticketPriceMap.has(ticketPriceKey1)) {
              ticketPrice = Train.ticketPriceMap.get(ticketPriceKey1)
            } else if (Train.ticketPriceMap.has(ticketPriceKey2)) {
              ticketPrice = Train.ticketPriceMap.get(ticketPriceKey2)
            } else {
              ticketPrice = Train.baseTicketPrice * this.adjustmentForDistance(fromToKey)
              Train.ticketPriceMap.set(ticketPriceKey1, ticketPrice)
            }
            // above to save ticket price caclulation time on subsequent lookups for the same route.
            earnings = Math.floor(ticketPrice * adjustedBoarding)
            totalEarnings += earnings
            // if(adjustedBoarding>0 && earnings==0) debugger;
            // if (this.trainNumber === 2) {
            //   console.log(`Train ${this.trainNumber} boarding from station ${fromKey} to station ${toKeyInMap}: ${currentBoarding} passengers, adjusted boarding: ${adjustedBoarding} passengers, ticket sale per passenger: ${ticketPrice}, total ticket sale: ${ticketPrice * adjustedBoarding}`)
            // }
            this.passengerMap.set(fromToKey, adjustedBoarding)
          }
        }
        this.financials.incrementRevenueFromTickets(this.getCurrentTimeIndex(), this.trainNumber, totalEarnings)

        const prevPassengersOnBoard = this.passengersOnBoard
        // Instead of totalBoarding we should be using adjustedBoarding
        // this.passengersOnBoard = this.passengersOnBoard + totalBoarding - totalDeboarding
        this.passengersOnBoard = this.passengersOnBoard + totalAdjustedBoarding - totalDeboarding
        
        const passengerMetrics = {
          deboarding: totalDeboarding,
          boarding: totalAdjustedBoarding,
          onboard: this.passengersOnBoard,
          unableToBoard,
          earnings: totalEarnings,
        }

        this.stationVisitContext = {
          trainType: 'passenger',
          stationName: station.name,
          isTerminal: isTerminalForCurrentDirection,
          metrics: passengerMetrics
        }

        if (isTerminalForCurrentDirection) {
          this.logStationOperation('arrival', this.stationVisitContext)
        }

        const existingPopupInfo = this.popups.getPopupInfo(station.x, station.y)
        // this.displayInfo(existingPopupInfo, station.x, station.y)
      }
      if (this.trainType == 'freight') {
        // For freight trains, we can assume that they take a fixed amount of time at each station for loading and unloading. 
        // We can use the remainingDwellTime variable to control the loading and unloading time at the station. 
        // The train will stop at the station for a certain number of ticks which is determined by the dwell time of the station. 
        // This way we can create a realistic effect of the freight train stopping at the station for loading and unloading.
        atAStation = true
        if (this.lastProcessedStationNumber === station.stationNumber) continue  // already processed this visit, skip
        this.lastProcessedStationNumber = station.stationNumber
        this.remainingDwellTime = station.stationNumber != minStationNumber && station.stationNumber != maxStationNumber ? station.dwellTime : 0
        // calculate the total amount of raw material required by all the stations on the route ahead of this station.
        // const isTerminalForCurrentDirection = (!this.isReturning && station.stationNumber === maxStationNumber) || (this.isReturning && station.stationNumber === minStationNumber)
        // const trainIsReturning = isTerminalForCurrentDirection ? !this.isReturning : this.isReturning
        let totalRawMaterialDemand = 0
        //we are already at a station

        // we first check if there is demand for raw material at this station
        // and if there is stock available in the train then we unload the raw material
        // and charge for it

        const demand = this.rawMaterialDemand.demandAt(station.x, station.y)
        // console.log(`Train ${this.trainNumber} at station ${station.stationNumber} has raw material demand of ${demand} units and raw material on board is ${this.rawMaterialOnBoard} units`)
        let totalUnloading = 0
        if (demand > 0) {
          totalUnloading = Math.min(demand, this.rawMaterialOnBoard)
          //earn revenue based on the amount of raw material unloaded and a fixed price per unit of raw material to keep it simple. 
          // We can also add a multiplier based on the distance between the from station and to station to make it more realistic 
          // but for now we will keep it simple with a fixed price per unit of raw material.
          this.financials.incrementRevenueFromRawMaterial(this.getCurrentTimeIndex(), this.trainNumber, totalUnloading * Train.rawMaterialChargePerUnit)
          this.rawMaterialOnBoard -= totalUnloading
          this.rawMaterialDemand.decreaseDemand(station.x, station.y, totalUnloading)
          // console.log(`Train ${this.trainNumber} at station ${station.stationNumber} unloaded ${totalUnloading} units of raw material, remaining on board: ${this.rawMaterialOnBoard} money earned: ${totalUnloading * Train.rawMaterialChargePerUnit}`)
        }

        for (const nextStation of this.stations) {
          if (!trainIsReturning && (nextStation.stationNumber > station.stationNumber) ||
            trainIsReturning && (nextStation.stationNumber < station.stationNumber)) {
            const demand = this.rawMaterialDemand.demandAt(nextStation.x, nextStation.y)
            // console.log(`Train ${this.trainNumber} looking ahead at station ${nextStation.stationNumber} with raw material demand of ${demand} units`)
            totalRawMaterialDemand += demand
          }
        }
        // console.log(`Train ${this.trainNumber} total raw material demand for upcoming stations is ${totalRawMaterialDemand} units and available capacity on train is ${(this.numCoaches * Train.rawMaterialCapacityPerFreightCoach) - this.rawMaterialOnBoard} units`)

        //let us load the train with this raw material if the suppy is available at the station
        let rawMaterialAvailable = this.rawMaterialSupply.availableAt(station.x, station.y)
        // console.log(`Train ${this.trainNumber} checking raw material supply at station ${station.stationNumber} with available raw material of ${rawMaterialAvailable} units`)

        let capacity = this.numCoaches * Train.rawMaterialCapacityPerFreightCoach
        let availableCapacity = capacity - (this.rawMaterialOnBoard ?? 0)
        let rawMaterialLoaded = Math.min(totalRawMaterialDemand - this.rawMaterialOnBoard, rawMaterialAvailable, availableCapacity)

        if (rawMaterialLoaded > 0) {
          this.rawMaterialOnBoard += rawMaterialLoaded
          this.rawMaterialSupply.decreaseRawMaterial(station.x, station.y, rawMaterialLoaded)
        }

        const freightMetrics = {
          unloading: totalUnloading,
          rawMaterialLoaded,
          rawMaterialOnBoard: this.rawMaterialOnBoard,
          unableToLoad: totalRawMaterialDemand - this.rawMaterialOnBoard,
          earnings: totalUnloading * Train.rawMaterialChargePerUnit
        }

        this.stationVisitContext = {
          trainType: 'freight',
          stationName: station.name,
          isTerminal: isTerminalForCurrentDirection,
          metrics: freightMetrics
        }

        if (isTerminalForCurrentDirection) {
          this.logStationOperation('arrival', this.stationVisitContext)
        }
        const existingPopupInfo = this.popups.getPopupInfo(station.x, station.y)
      }
    }

    if (!atAStation) {
      if (this.stationVisitContext) {
        this.logStationOperation('departure', this.stationVisitContext)
        this.stationVisitContext = null
      }
      this.lastProcessedStationNumber = null  // train has left the station, allow retriggering next visit
    }

    if (this.awaitingTurnaround && atAStation) {
      // Delay direction flip until terminal station processing is complete,
      // otherwise terminal deboarding/arrival metrics can be skipped.
      this.count = 0
      this.ticks = 0
      this.isReturning = !this.isReturning
      this.tripNumber++
      this.lastSmokeEmitTick = 0
      this.awaitingTurnaround = false
    }

    const heading = Number.isFinite(direction) ? direction : 0
    const laneToOffsetMultiplier = [0, -1, 1]
    const normalizedLane = Number.isFinite(this.lane) ? ((this.lane % 3) + 3) % 3 : 0
    const laneOffsetMagnitude = laneToOffsetMultiplier[normalizedLane] * Train.widthEngine*0.3
    const engineOffsetMagnitude = this.isOnParallelSegment(x, y) ? laneOffsetMagnitude : 0
    if (!this.debugLaneLogged) {
      console.log(`[ParallelLaneVisual] train=${this.trainNumber}, lane=${this.lane}, normalizedLane=${normalizedLane}, offsetPx=${laneOffsetMagnitude}, parallelCells=${this.parallelSegmentCells?.size ?? 0}`)
      this.debugLaneLogged = true
    }
    const laneOffsetX = -Math.sin(heading) * engineOffsetMagnitude
    const laneOffsetY = Math.cos(heading) * engineOffsetMagnitude

    const engineDrawX = x + laneOffsetX
    const engineDrawY = y + laneOffsetY

    this.ctx.save()
    this.ctx.fillStyle = this.color
    this.ctx.translate(engineDrawX, engineDrawY)
    this.ctx.rotate(heading)
    this.ctx.translate(-1 * Train.lengthEngine * 0.5, -1 * Train.widthEngine * 0.5)
    this.drawEngine(0, 0)
    this.ctx.restore()

    const occupiedIntersections = new Map()
    this.setIntersection(occupiedIntersections, x, y)

    const getCoachGap = (coachIndex, spacingScale = 1) => {
      const firstCoachGap = (Train.lengthEngine + Train.lengthCoach + 2 * d) * 0.5
      return firstCoachGap + ((Train.lengthCoach + d) * coachIndex * spacingScale)
    }

    // Keep intersection occupancy based on full simulated train length.
    for (let coachNum = 0; coachNum < this.numCoaches; coachNum++) {
      const gap = getCoachGap(coachNum)
      const { x: x2, y: y2 } = this.getPosition(-1 * gap)
      this.setIntersection(occupiedIntersections, x2, y2)
    }

    const visibleCoachCount = Math.min(this.numCoaches, this.maxVisualCoaches)
    const simulatedCoachRangeMax = this.hasExplicitVisualCoachCap
      ? Math.max(0, Math.min(this.numCoaches, this.maxVisualCoaches) - 1)
      : Math.max(0, this.numCoaches - 1)
    for (let visualIndex = 0; visualIndex < visibleCoachCount; visualIndex++) {
      const simulatedCoachIndex = visibleCoachCount === 1
        ? 0
        : Math.round((visualIndex / (visibleCoachCount - 1)) * simulatedCoachRangeMax)
      const gap = getCoachGap(simulatedCoachIndex, this.visualLengthScale)
      const { x: x2, y: y2, direction: direction2 } = this.getPosition(-1 * gap)

      const coachHeading = Number.isFinite(direction2) ? direction2 : 0
      const coachOffsetMagnitude = this.isOnParallelSegment(x2, y2) ? laneOffsetMagnitude : 0
      const coachOffsetX = -Math.sin(coachHeading) * coachOffsetMagnitude
      const coachOffsetY = Math.cos(coachHeading) * coachOffsetMagnitude
      const coachDrawX = x2 + coachOffsetX
      const coachDrawY = y2 + coachOffsetY

      this.ctx.save()
      this.ctx.fillStyle = this.color
      this.ctx.translate(coachDrawX, coachDrawY)
      this.ctx.rotate(coachHeading)
      this.ctx.translate(-10, -1 * Train.widthCoach * 0.5)
      this.drawCoach()

      this.ctx.restore()
    }

    this.maybeEmitSmoke(engineDrawX, engineDrawY, heading, currSpeed)
    this.drawSmokePuffs()

    this.syncIntersections(occupiedIntersections)
    return { x, y, width: Train.lengthEngine + Train.lengthCoach * this.numCoaches + 5 }
  }

  maybeEmitSmoke(engineX, engineY, heading, currSpeed) {
    
    if (this.userPaused || this.dwellPaused) {
      return
    }
    
    const smokeSetting = this.normalizeSmokeSetting(this.smokeSetting)
    if (smokeSetting === 'off') {
      return
    }
    
    const emitScale = smokeSetting === 'low' ? 1.6 : 0.7
    // const emitEveryTicks = Math.max(4, Math.min(28, Math.round((Number(currSpeed) || 20) * 1.2 * emitScale)))
    const emitEveryTicks = this.trainType === 'passenger' ? 14 : 40
    console.log(`Train ${this.trainNumber} smoke emit every ${emitEveryTicks} ticks (currSpeed=${currSpeed}, smokeSetting=${smokeSetting})`)
    if (this.ticks - this.lastSmokeEmitTick < emitEveryTicks) {
      return
    }
    
    this.lastSmokeEmitTick = this.ticks
    const chimneyRadius = Train.widthEngine * Train.chimney_r / 100
    const frontOffset = -0.5 * Train.lengthEngine * 0.42 + chimneyRadius * 0.9
    const chimneyX = engineX + Math.cos(heading) * frontOffset
    const chimneyY = engineY + Math.sin(heading) * frontOffset
    const lateralJitterX = -Math.sin(heading) * ((Math.random() - 0.5) * 1.6)
    const lateralJitterY = Math.cos(heading) * ((Math.random() - 0.5) * 1.6)
    
    const puffCount = smokeSetting === 'low' ? 1 : 2
    for (let i = 0; i < puffCount; i++) {
      const puff = {
        x: chimneyX + lateralJitterX + (-Math.sin(heading) * (i * 1.4)),
        y: chimneyY + lateralJitterY + (Math.cos(heading) * (i * 1.4)),
        r: 3.5 + Math.random() * 3.1,
        grow: 0.16 + Math.random() * 0.12,
        vx: -Math.cos(heading) * (0.1 + Math.random() * 0.08) + (Math.random() - 0.5) * 0.07,
        vy: -Math.sin(heading) * (0.1 + Math.random() * 0.08) + (Math.random() - 0.5) * 0.07 - 0.06,
        life: 85 + Math.floor(Math.random() * 55),
        maxLife: 85 + Math.floor(Math.random() * 55),
        alphaMax: smokeSetting === 'low' ? 0.24 : 0.5
      }
      
      this.smokePuffs.push(puff)
    }
    const maxPuffs = smokeSetting === 'low' ? 24 : Train.maxSmokePuffs
    if (this.smokePuffs.length > maxPuffs) {
      this.smokePuffs.splice(0, this.smokePuffs.length - maxPuffs)
    }
  }
  
  drawSmokePuffs() {

    if (!this.smokePuffs.length) {
      return
    }
    
    // if(this.trainNumber===1) debugger
    this.ctx.save()
    for (let i = this.smokePuffs.length - 1; i >= 0; i--) {
      const puff = this.smokePuffs[i]
      puff.x += puff.vx
      puff.y += puff.vy
      puff.r += puff.grow
      puff.life -= 1

      const t = puff.maxLife > 0 ? (puff.life / puff.maxLife) : 0
      const alphaLimit = Number.isFinite(puff.alphaMax) ? puff.alphaMax : 0.28
      const alpha = Math.max(0, Math.min(alphaLimit, t * alphaLimit))
      if (puff.life <= 0 || alpha <= 0) {
        this.smokePuffs.splice(i, 1)
        continue
      }

      this.ctx.beginPath()
      this.ctx.fillStyle = `rgba(160,160,160,${alpha})`
      this.ctx.arc(puff.x, puff.y, puff.r, 0, Math.PI * 2)
      this.ctx.fill()
    }
    this.ctx.restore()
  }

  drawEngine(x, y) {

    let chimneyRadius = Train.widthEngine * Train.chimney_r / 100

    this.ctx.save()
    this.ctx.beginPath()
    this.ctx.rect(x, y, Train.lengthEngine * 3 / 4, Train.widthEngine)
    this.ctx.fill()
    this.ctx.closePath()

    //steam outlet
    this.ctx.beginPath()
    this.ctx.moveTo(x + Train.lengthEngine * 0.5 + chimneyRadius, y + Train.widthEngine * 0.5)
    this.ctx.arc(x + Train.lengthEngine * 0.5 + chimneyRadius, y + Train.widthEngine * 0.5, chimneyRadius, 0, 2 * Math.PI)
    this.ctx.fillStyle = Train.smokeColor
    this.ctx.fill()
    this.ctx.closePath()

    //front portion
    this.ctx.beginPath()
    this.ctx.moveTo(x + Train.lengthEngine * 3 / 4, y)
    this.ctx.quadraticCurveTo(x + Train.lengthEngine, y + Train.widthEngine * 0.5, x + Train.lengthEngine * 3 / 4, y + Train.widthEngine)
    // this.ctx.lineTo(x+Train.lengthEngine*3/4, y+Train.widthEngine)
    this.ctx.fillStyle = this.color
    this.ctx.fill()
    this.ctx.closePath()

    //Coal section
    this.ctx.beginPath()
    this.ctx.rect(x, y, Train.lengthEngine / 4, Train.widthEngine)
    this.ctx.fillStyle = `#000`
    this.ctx.fill()
    this.ctx.closePath()
    this.ctx.restore()

  }

  drawCoach() {

    this.ctx.save()
    this.ctx.beginPath()
    this.ctx.fillStyle = '#000'
    if (this.trainType === 'passenger') {
      //draw the gangway between the engine and the first coach
      //and each coach and next.
      this.ctx.fillRect(Train.lengthCoach,3, 4, Train.widthCoach-6)
      // this.ctx.closePath()
    } else if (this.trainType === 'freight') {
      //draw 2 couplings between the engine and the first freight wagon   
      //and each coach and next.
      const couplingWidth = 2
      const couplingHeight = 2
      this.ctx.fillRect(Train.lengthCoach, 3, couplingWidth, couplingHeight)
      this.ctx.fillRect(Train.lengthCoach, Train.widthCoach - 3 - couplingHeight, couplingWidth, couplingHeight)
      // this.ctx.closePath()
    }
    this.ctx.closePath()
    this.ctx.beginPath()
    const gradient = this.ctx.createLinearGradient(0, 0, Train.lengthCoach, Train.widthCoach)
    gradient.addColorStop(0, Train.coachColor)
    gradient.addColorStop(1, '#333')
    this.ctx.fillStyle = gradient
    this.ctx.strokeStyle = '#333'
    this.ctx.rect(0, 0, Train.lengthCoach, Train.widthCoach)
    this.ctx.fill()
    this.ctx.stroke()
    this.ctx.closePath()
    this.ctx.restore()

  }

  getPosition(offset) {
    //how far has the Train travelled
    const distance = this.count + offset
    return this.track.getPoseAtDistance(distance, this.isReturning)
  }

  setIntersection(intersectionsMap, x, y) {
    // this method does not use the Intersections object 
    // to store the intersection; it only queries it to find 
    // the intersection at the given canvas position and then 
    // updates the provided intersectionsMap which is created
    // outside this method and passed in as an argument.
    if (x < this.intersections.offsetX || y < this.intersections.offsetY) return

    const intersection = this.intersections.getCellAtPosition(x, y, Train.intersectionDist)
    if (!intersection) return

    const key = `${intersection.row},${intersection.col}`
    intersectionsMap.set(key, intersection)
  }

  syncIntersections(nextIntersections) {
    let hasNewIntersection = false

    nextIntersections.forEach((intersection, key) => {
      if (!this.activeIntersections.has(key)) {
        this.displayIntersection(intersection.row, intersection.col)
        this.intersections.updateIntersection(intersection.row, intersection.col, this.trainNumber, this.lane)
        hasNewIntersection = true
      }
    })

    this.activeIntersections.forEach((intersection, key) => {
      if (!nextIntersections.has(key)) {
        this.clearIntersection(intersection.row, intersection.col)
        this.intersections.updateIntersection(intersection.row, intersection.col, null, this.lane)
      }
    })

    if (hasNewIntersection) {
      // this.beep.play()
    }

    this.activeIntersections = nextIntersections
  }

  displayIntersection(row, col) {
    const { x, y } = this.intersections.getCanvasPoint(row, col)
    this.ctxTemp.fillStyle = 'red'
    this.ctxTemp.beginPath()
    this.ctxTemp.arc(x, y, 5, 0, Math.PI * 2)
    this.ctxTemp.fill()
  }

  clearIntersection(row, col) {
    const { x, y } = this.intersections.getCanvasPoint(row, col)
    this.ctxTemp.clearRect(x - 5, y - 5, 10, 10)
  }

  addStation(station) {
    this.track.addStation(station)
    this.stations = this.track.getStations() // update the stations reference after adding a new station to the track
  }

  getNumStations() {
    //used for calculating the station maintenance/operating cost for this train.
    return this.stations.length
  }

  consumeDistanceTraveledInTimeUnit() {
    const distance = this.distanceTraveledInTimeUnit
    this.distanceTraveledInTimeUnit = 0
    return distance
  }

  adjustmentForDistance(fromToKey) {
    // we can have a simple adjustment factor based on the distance between the from station and to 
    // station to make it more realistic. For example, we can assume that the ticket price increases 
    // by 10% for every 100 units of distance traveled. This is a simplification but it should work for our purposes.
    const [fromStation, toStation] = fromToKey.split('-').map(Number)
    const fromStationObj = this.stations.find(st => st.stationNumber === fromStation)
    const toStationObj = this.stations.find(st => st.stationNumber === toStation)
    const fromCoords = [fromStationObj.x, fromStationObj.y]
    const toCoords = [toStationObj.x, toStationObj.y]
    const distance = Math.sqrt(Math.pow(toCoords[0] - fromCoords[0], 2) + Math.pow(toCoords[1] - fromCoords[1], 2))
    const adjustmentFactor = 1 + (distance / 100) * 0.10
    return adjustmentFactor
  }

  getNumCoachesOrFreightWagons() {
    return this.numCoaches
  }

  extendTrain(positionsForExtendTrain) {
    // We pass these positions to the track to extend it and get the new station location
    const { track, stationLocation } = this.track.extendTrack(positionsForExtendTrain)
    this.track = track
    this.parallelSegmentCells = this.buildParallelSegmentCellSet()
    return stationLocation
  }

  updateInfoOnTrainOperations(typeOfTrain) {
    const div = document.getElementById(`infotrainoperations${this.trainNumber}`)
    const currentTimeIndex = this.getCurrentTimeIndex()
    if (div) {
      div.replaceChildren()
      const table = document.createElement('table')
      const thead = document.createElement('thead')
      const headerRow = document.createElement('tr')
      const th1 = document.createElement('th')
      th1.textContent = 'Time'
      const th2 = document.createElement('th')
      th2.textContent = 'Trip#'
      const th3 = document.createElement('th')
      th3.textContent = 'Station'
      const th4 = document.createElement('th')
      th4.textContent = 'Event'
      const th5 = document.createElement('th')
      th5.textContent = typeOfTrain === 'passenger' ? 'DeBoarding' : 'Unloading'
      const th6 = document.createElement('th')
      th6.textContent = typeOfTrain === 'passenger' ? 'Boarding' : 'Loading'
      const th7 = document.createElement('th')
      th7.textContent = typeOfTrain === 'passenger' ? 'Onboard' : 'Onboard'
      const th8 = document.createElement('th')
      th8.textContent = typeOfTrain === 'passenger' ? 'Unable to Board' : 'Unable to Load'
      const th9 = document.createElement('th')
      th9.textContent = 'Earnings'
      headerRow.appendChild(th1)
      headerRow.appendChild(th2)
      headerRow.appendChild(th3)
      headerRow.appendChild(th4)
      headerRow.appendChild(th5)
      headerRow.appendChild(th6)
      headerRow.appendChild(th7)
      headerRow.appendChild(th8)
      headerRow.appendChild(th9)
      headerRow.style.backgroundColor = this.color
      thead.appendChild(headerRow)
      table.appendChild(thead)
      const tbody = document.createElement('tbody')
      const trainEntries = this.trainInfo.getTrainInfoForTrainAndTimeIndex(this.trainNumber, currentTimeIndex) ?? []
      trainEntries.forEach(obj => {
        const row = document.createElement('tr')
        const td1 = document.createElement('td')
        td1.textContent = currentTimeIndex
        const td2 = document.createElement('td')
        td2.textContent = obj.tripNumber
        const td3 = document.createElement('td')
        td3.textContent = obj.stationName
        const td4 = document.createElement('td')
        td4.textContent = obj.eventType ?? (obj.stationName?.includes('(arrival)') ? 'arrival' : (obj.stationName?.includes('(departure)') ? 'departure' : ''))
        const td5 = document.createElement('td')
        td5.textContent = typeOfTrain === 'passenger' ? obj.deboarding : obj.unloading
        const td6 = document.createElement('td')
        td6.textContent = typeOfTrain === 'passenger' ? obj.boarding : obj.rawMaterialLoaded
        const td7 = document.createElement('td')
        td7.textContent = typeOfTrain === 'passenger' ? obj.onboard : obj.rawMaterialOnBoard
        const td8 = document.createElement('td')
        td8.textContent = typeOfTrain === 'passenger' ? obj.unableToBoard : obj.unableToLoad
        const td9 = document.createElement('td')
        td9.textContent = Math.floor(obj.earnings / 1000) + 'K'
        row.appendChild(td1)
        row.appendChild(td2)
        row.appendChild(td3)
        row.appendChild(td4)
        row.appendChild(td5)
        row.appendChild(td6)
        row.appendChild(td7)
        row.appendChild(td8)
        row.appendChild(td9)
        tbody.appendChild(row)
      })
      table.appendChild(tbody)
      div.appendChild(table)
    }
  }

  logStationOperation(eventType, visitContext) {
    if (!visitContext) return

    const { trainType, stationName, isTerminal, metrics } = visitContext
    const eventMetrics = { ...metrics }

    if (trainType === 'freight' && isTerminal && eventType === 'departure') {
      eventMetrics.unloading = 0
      eventMetrics.earnings = 0
    }

    if (trainType === 'passenger' && isTerminal && eventType === 'departure') {
      eventMetrics.deboarding = 0
      // eventMetrics.earnings = 0
    }

    if (trainType === 'passenger' && isTerminal && eventType === 'arrival') {
      eventMetrics.boarding = 0
      eventMetrics.earnings = 0
      eventMetrics.onboard = 0
    }

    this.trainInfo.setTrainInfo(this.trainNumber, this.getCurrentTimeIndex(), {
      tripNumber: this.tripNumber,
      stationName,
      eventType,
      ...eventMetrics
    })
    this.updateInfoOnTrainOperations(trainType)
  }
}
export {
  Train
}