"use strict";
import { makeDraggable } from './utility.js'
class Train {
  static lengthEngine = 40
  static widthEngine = 14
  static lengthCoach = 20
  static widthCoach = 12
  static chimney_r = 30
  static smokeColor = `#222`
  static coachColor = `#00ff00`
  static intersectionDist = 10
  static maxNumCoaches = 15
  static maxNumFreightWagons = 100
  static minNumCoaches = 2
  static coachPassengerCapacity = 100
  static baseTicketPrice = 300
  static rawMaterialCapacityPerFreightCoach = 100000 // fixed raw material capacity per freight coach to keep it simple. We can adjust this as needed to make it more realistic.
  static rawMaterialChargePerUnit = 100 // fixed charge per unit of raw material to keep it simple. Revenue is calculated based on the amount of raw material unloaded at the station.
  static ticketPriceMap = new Map() // key is from row,col to row,col and value is the ticket price for that route. 
  // We populate this as we go unless the ticket price is already in the map. 


  constructor({
    ctx,
    ctxTemp,
    speed,
    track,
    color,
    numCoaches,
    trainName,
    delayBeforeStart = 1,
    trainNumber,
    intersections,
    financials,
    travelPopulation,
    rawMaterialDemand,
    rawMaterialSupply,
    getCurrentTimeIndex,
    trainType = 'passenger',
    visualLengthScale = 1,
    maxVisualCoaches,
    popups
  } = {}) {
    this.ctx = ctx
    this.ctxTemp = ctxTemp
    this.track = track
    this.color = color
    this.trainType = trainType
    // speed parameter: 1=slowest, 20=fastest. Internally inverted to a frame-step divisor (lower=faster).
    // Freight trains run at a fixed half-of-maximum speed (divisor 11 = parameter 10 out of 20).
    this.speed = this.trainType == 'passenger' ? Math.max(1, 21 - speed) : 11
    const maxInitialCoaches = this.trainType === 'freight' ? Train.maxNumFreightWagons : Train.maxNumCoaches
    this.numCoaches = numCoaches ? Math.min(Math.max(numCoaches, Train.minNumCoaches), maxInitialCoaches) : Math.floor((Train.minNumCoaches + Train.maxNumCoaches) / 2)
    this.ticks = 0
    this.count = 0
    this.isReturning = false
    this.trainName = trainName
    this.trainNumber = trainNumber
    this.visualLengthScale = Math.max(0.2, Math.min(1, visualLengthScale))
    this.hasExplicitVisualCoachCap = maxVisualCoaches != null
    this.maxVisualCoaches = Math.max(1, this.hasExplicitVisualCoachCap ? maxVisualCoaches : this.numCoaches)
    this.paused = false
    this.userPaused = false
    this.dwellPaused = false
    this.delayBeforeStart = delayBeforeStart
    this.intersections = intersections
    this.activeIntersections = new Map()
    this.trainlength = Train.lengthEngine + (Train.lengthCoach + 2) * this.numCoaches
    this.financials = financials
    this.getCurrentTimeIndex = getCurrentTimeIndex
    this.dysfunctional = false
    this.repairTime = 5000 //time in ticks for which the train will be dysfunctional after a collision. This is to simulate the time taken for the train to be repaired after a collision.
    this.repairticks = 0
    // we need stations here to calculate the number of passengers traveling from one station to another station on the route of the train. This is used to calculate the revenue generated by the train operations based on the number of passengers on board and the distance traveled.
    // and also to stop at each station for a certain amount of time.
    this.stations = track.getStations()
    this.beep = new Audio('./beep.mp3')
    // key is the from station and to station coordinates and value is the number of passengers going on that route. For example, 
    // if there are 10 passengers going from station A to station B, then the key will be "Ax,Ay-Bx,By" and the value will be 10. This is used to calculate the revenue generated by the train operations based on the number of passengers on board and the distance traveled.
    // this is to be populated when the station is added. Let us say that we wanto calculate
    // the number of passengers traveling from station A to station B, 
    // let us say that travelPopulation for A is TA and travelPopulation for B is TB
    // then number is TA*TB/TT where TT is the total travel population.
    // When the train starts at the Starting point it takes in passengers for all the
    // stations on the route. When the train reaches the first station on route, it unloads the
    // passengers for that station and takes on the passengers for all the following stations and so on.
    // In our data model, station is part of the track and hence we will need to access the station information 
    // from the track to get the coordinates of the station and then use that to get the travel population for that 
    // station to calculate the number of passengers traveling from that station to all the following stations on the route. 
    // This is a simplification but it should work for our purposes.
    this.passengerMap = new Map()
    this.travelPopulation = travelPopulation
    this.totalTravelPopulation = Array.from(this.travelPopulation.travelPopulation.values()).reduce((a, b) => a + b.population, 0)
    this.passengersOnBoard = 0
    this.lastProcessedStationNumber = null  // prevents boarding/deboarding from firing on every frame while at a station
    this.remainingDwellTime = 0
    this.infoText = ''
    // this.infoTextTicks = 0
    this.freightTrainDwellTime = 200 // fixed dwell time for freight trains at each station for loading and unloading. This can be adjusted as needed.
    this.rawMaterialDemand = rawMaterialDemand
    this.rawMaterialSupply = rawMaterialSupply
    this.rawMaterialOnBoard = 0
    this.distanceTraveledInTimeUnit = 0
    this.popups = popups
  }

  addCoach() {
    const maxAllowedCoaches = this.trainType === "freight" ? Train.maxNumFreightWagons : Train.maxNumCoaches
    if (this.numCoaches >= maxAllowedCoaches) return

    this.numCoaches += 1
    if (!this.hasExplicitVisualCoachCap) {
      this.maxVisualCoaches = this.numCoaches
    }
    this.trainlength = Train.lengthEngine + (Train.lengthCoach + 2) * this.numCoaches
  }
  removeCoach() {
    if (this.numCoaches > Train.minNumCoaches) {
      this.numCoaches -= 1
      if (!this.hasExplicitVisualCoachCap) {
        this.maxVisualCoaches = this.numCoaches
      }
      this.trainlength = Train.lengthEngine + (Train.lengthCoach + 2) * this.numCoaches
    }
  }

  setDysfunctional(state) {
    this.dysfunctional = state
    if (state) {
      this.activeIntersections.forEach((intersection, key) => {
        this.clearIntersection(intersection.row, intersection.col)
        this.intersections.updateIntersection(intersection.row, intersection.col, null)
      })
    } else {
      //repair is done, reset the repair ticks and allow the train to move again
      this.repairticks = 0
      //also after the train is repaired
      //set the train to its original position
      this.count = 0
      this.isReturning = false
      this.paused = false
      this.userPaused = false
    }
  }

  startStop() {
    this.userPaused = !this.userPaused
  }

  setUserPaused(state) {
    this.userPaused = !!state
  }

  speedUp() {
    this.speed = Math.max(1, this.speed - 1)
  }

  slowDown() {
    this.speed = Math.min(20, this.speed + 1)
  }


  draw() {

    // we want to start the train gradually from a zero speed to avoid the jarring effect of the train suddenly appearing at full speed. So we can use the ticks variable to control the speed of the train in the initial phase. The train will start moving after a certain number of ticks have passed, which is determined by the delayBeforeStart variable. We can also use the ticks variable to control the speed of the train in the initial phase. The train will start moving after a certain number of ticks have passed, which is determined by the delayBeforeStart variable. This way we can create a smooth acceleration effect for the train when it starts moving.
    const step1 = this.trainType == "passenger" ? 20 - Math.floor(this.speed * 1 / 6) : 20
    const step2 = this.trainType == "passenger" ? 20 - Math.floor(this.speed * 2 / 6) : 20
    const step3 = this.trainType == "passenger" ? 20 - Math.floor(this.speed * 3 / 6) : 20
    const step4 = this.trainType == "passenger" ? 20 - Math.floor(this.speed * 4 / 6) : 20
    const step5 = this.trainType == "passenger" ? 20 - Math.floor(this.speed * 5 / 6) : 20

    const currSpeed = this.ticks < 50 ? step1 : this.ticks < 150 ? step2 : this.ticks < 250 ? step3 : this.ticks < 350 ?
      step4 : this.ticks < 450 ? step5 : this.speed

    if (this.dysfunctional) {
      // If the train is dysfunctional, we don't update its position or draw it.
      // till a certain time has passed which is the time needed for th train 
      // to be repaired.
      const healthBar = document.querySelector(`#health${this.trainNumber}`)
      if (this.repairticks % 1000 == 0) {
        //increase the width of the health bar to indicate the progress of the repair
        if (healthBar) {
          const width = (this.repairticks / this.repairTime) * 20
          healthBar.style.width = `${width}px`
        }
      }
      this.repairticks++
      if (this.repairticks >= this.repairTime) {
        this.setDysfunctional(false)
        if (healthBar) {
          healthBar.style.width = `20px`
        }
      }
      return
    }



    //draw is called on each frame from the game loop
    const d = 2 //distance between one coach and the next

    // Only increment ticks and dwell time when game is not paused
    if (!this.userPaused) {
      this.ticks++
      this.remainingDwellTime--
    }

    //train is not drawn till this.ticks reach a certain level
    if (this.ticks < this.delayBeforeStart * 100) return

    //Also we do not draw the train unless the whole train has reached the starting point. 
    //This is to avoid the train appearing to be cut off at the beginning of the track
    // if (segment && segment.startDistance < this.trainlength) return

    // we have to set the position of the engine based on 
    // how far it has moved on the tracks
    // console.log(this.tick)
    // console.log(`Train ${this.trainName} ticks:${this.ticks} ,globalTicks: ${globalThis.globalTicks}, count:${this.count}`)
    this.dwellPaused = this.remainingDwellTime > 0 ? true : false

    if ((this.ticks % currSpeed == 0) && !this.userPaused && !this.dwellPaused) {
      //this controls the overall speed of the train. The lower the engineSpeed, the faster the train moves. The train moves one step after every engineSpeed number of frames
      const previousCount = this.count
      const distanceStep = 3
      this.count += distanceStep
      let distanceMoved = distanceStep
      if (this.track.totalLength > 0 && this.count >= this.track.totalLength) {
        distanceMoved = Math.max(0, this.track.totalLength - previousCount)
        this.count = 0
        this.ticks = 0
        this.isReturning = !this.isReturning
        // console.log(`Train ${this.trainName} is now ${this.isReturning ? 'returning' : 'starting a new trip'}`)
      }
      this.distanceTraveledInTimeUnit += distanceMoved
    }

    let { x, y, direction, segment } = this.getPosition(0)
    // console.log(`Train ${this.trainName} position: x:${x}, y:${y}, direction:${direction}, segment:${segment ? `start(${segment.startx},${segment.starty}), end(${segment.endx},${segment.endy})` : 'null'}`)

    // this.infodiv.style = `top: ${y}px; left: ${x}px;`
    //location is saved in the train object 
    this.x = x
    this.y = y
    // this.ctx.fillText(`T${this.trainNumber}`, x - 10, y - 10)

    // this section for calculating the number of passengers
    // boarding and alighting at each station and the revenue generated by the train operations based on the number of passengers on board and the distance traveled. We assume that all passengers get on the train at the starting point and get off at their destination station. This is a simplification but it should work for our purposes.
    let atAStation = false
    const stationNumbers = this.stations.map(st => st.stationNumber)
    const minStationNumber = stationNumbers.length ? Math.min(...stationNumbers) : 0
    const maxStationNumber = stationNumbers.length ? Math.max(...stationNumbers) : 0
    for (const station of this.stations) {
      if ((Math.abs(x - station.x) < 5) && (Math.abs(y - station.y) < 5)) {
        const isTerminalForCurrentDirection = (!this.isReturning && station.stationNumber === maxStationNumber) || (this.isReturning && station.stationNumber === minStationNumber)
        const trainIsReturning = isTerminalForCurrentDirection ? !this.isReturning : this.isReturning
        if (this.trainType == 'passenger') {
          //reached a station. Set the dwell time
          let totalDeboarding = 0
          let totalBoarding = 0
          const thisStationKey = `${station.stationNumber}`
          atAStation = true
          if (this.lastProcessedStationNumber === station.stationNumber) continue  // already processed this visit, skip
          this.lastProcessedStationNumber = station.stationNumber
          this.remainingDwellTime = station.stationNumber != minStationNumber && station.stationNumber != maxStationNumber ? station.dwellTime : 0
          //deboarding loop
          // for (const station of this.stations) {
          for (const fromToKey of this.passengerMap.keys()) {
            const [fromKey, toKeyInMap] = fromToKey.split('-')
            if (toKeyInMap === thisStationKey) {
              totalDeboarding += this.passengerMap.get(fromToKey)
              this.passengerMap.set(fromToKey, 0) // all passengers for that route get off at the destination station or we can delete this key
            }
          }
          // }
          //boarding loop
          // Here we calculate the number of passengers boarding the train at this station for all the following 
          // stations on the route. We can get the travel population for this station and then calculate the number 
          // of passengers boarding for each of the following stations on the route based on the travel population 
          // for those stations and the total travel population. This is a simplification but it should work for our purposes.


          const travelPopFrom = this.travelPopulation.travelPopulation.get(`${station.x},${station.y}`)?.population ?? 0
          for (const nextStation of this.stations) {
            if (!trainIsReturning && (nextStation.stationNumber > station.stationNumber) || trainIsReturning && (nextStation.stationNumber < station.stationNumber)) {
              // if (this.isReturning) debugger
              const toKey = `${nextStation.stationNumber}`
              const travelPopTo = this.travelPopulation.travelPopulation.get(`${nextStation.x},${nextStation.y}`)?.population ?? 0
              //add randomness of +- 30% to the number of passengers boarding to make it more realistic and to avoid having the same number of passengers boarding at each station for the same travel population numbers. This is because in reality, the number of passengers boarding at a station can vary even if the travel population is the same due to various factors such as time of day, day of week, special events, etc. This will add some variability to our simulation and make it more interesting.
              let boarding = Math.ceil(travelPopTo * travelPopFrom * (0.7 + 0.6 * Math.random()) / this.totalTravelPopulation)
              totalBoarding += boarding
              const routeKey = `${thisStationKey}-${toKey}`
              this.passengerMap.set(routeKey, boarding)
            }
          }

          const passengerCapacity = this.numCoaches * Train.coachPassengerCapacity
          //we fix the map only if the number of passengers trying to board the train exceeds the passenger capacity of the train. This is to avoid the situation where we have a large number of passengers trying to board the train and we end up with a negative number of passengers on board after deboarding.
          let proportionBoarding = 1
          let unableToBoard = 0
          if (totalBoarding + this.passengersOnBoard - totalDeboarding > passengerCapacity) {
            // if the number of passengers on board after boarding and deboarding exceeds the passenger capacity of the train, then we can assume that only the passengers that can fit in the train will board the train and the rest will not board the train. This is a simplification but it should work for our purposes.
            unableToBoard = totalBoarding + this.passengersOnBoard - totalDeboarding - passengerCapacity
            // proportionBoarding = (passengerCapacity - this.passengersOnBoard + totalDeboarding) / totalBoarding
            proportionBoarding = (totalBoarding-unableToBoard) / totalBoarding
          }
          totalBoarding = Math.floor(totalBoarding * proportionBoarding)
          for (const fromToKey of this.passengerMap.keys()) {
            const [fromKey, toKeyInMap] = fromToKey.split('-')
            if (fromKey === thisStationKey) {
              const currentBoarding = this.passengerMap.get(fromToKey)
              const adjustedBoarding = Math.floor(currentBoarding * proportionBoarding)
              const toStationObj = this.stations.find(st => st.stationNumber === parseInt(toKeyInMap))
              const ticketPriceKey1 = `${Math.floor(station.x / 100) + 1},${Math.floor(station.y / 100) + 1}-${Math.floor(toStationObj.x / 100) + 1},${Math.floor(toStationObj.y / 100) + 1}`
              const ticketPriceKey2 = `${Math.floor(toStationObj.x / 100) + 1},${Math.floor(toStationObj.y / 100) + 1}-${Math.floor(station.x / 100) + 1},${Math.floor(station.y / 100) + 1}`
              // following to save ticket price caclulation time on subsequent lookups for the same route. 
              let ticketPrice
              if (Train.ticketPriceMap.has(ticketPriceKey1)) {
                ticketPrice = Train.ticketPriceMap.get(ticketPriceKey1)
              } else if (Train.ticketPriceMap.has(ticketPriceKey2)) {
                ticketPrice = Train.ticketPriceMap.get(ticketPriceKey2)
              } else {
                ticketPrice = Train.baseTicketPrice * this.adjustmentForDistance(fromToKey)
                Train.ticketPriceMap.set(ticketPriceKey1, ticketPrice)
              }
              // above to save ticket price caclulation time on subsequent lookups for the same route.
              this.financials.incrementRevenueFromTickets(this.getCurrentTimeIndex(), this.trainNumber, ticketPrice * adjustedBoarding)
              if (this.trainNumber === 2) {
                console.log(`Train ${this.trainNumber} boarding from station ${fromKey} to station ${toKeyInMap}: ${currentBoarding} passengers, adjusted boarding: ${adjustedBoarding} passengers, ticket sale per passenger: ${ticketPrice}, total ticket sale: ${ticketPrice * adjustedBoarding}`)
              }
              this.passengerMap.set(fromToKey, adjustedBoarding)
            }
          }

          const prevPassengersOnBoard = this.passengersOnBoard
          this.passengersOnBoard = this.passengersOnBoard + totalBoarding - totalDeboarding
          // ticket sales is based on total boarding passengers and a distance-adjusted ticket price.
          // console.log(`Train ${this.trainNumber} at station ${thisStationKey} deboarded ${totalDeboarding} passengers, boarded ${totalBoarding} passengers, total passengers on board: ${this.passengersOnBoard}`)
          let infoText = ''
          if (station.stationNumber != minStationNumber && station.stationNumber != maxStationNumber) {
            infoText = `T${this.trainNumber} P: - ${totalDeboarding} + ${totalBoarding} = ${this.passengersOnBoard} | (${unableToBoard}??)`
          } else {
            infoText = `T${this.trainNumber} P: ${this.passengersOnBoard} | (${unableToBoard}??)`
          }
          // this.infoText = infoText
          // this.infoTextTicks = 400
          this.popups.addTrain({
            x: station.x,
            y: station.y,
            stationName: station.name,
            trainNumber: this.trainNumber,
            trainInfo: infoText,
          })
          const existingPopupInfo = this.popups.getPopupInfo(station.x, station.y)
          this.displayInfo(existingPopupInfo, station.x,station.y)
        }
        if (this.trainType == 'freight') {
          // For freight trains, we can assume that they take a fixed amount of time at each station for loading and unloading. 
          // We can use the remainingDwellTime variable to control the loading and unloading time at the station. 
          // The train will stop at the station for a certain number of ticks which is determined by the dwell time of the station. 
          // This way we can create a realistic effect of the freight train stopping at the station for loading and unloading.
          atAStation = true
          if (this.lastProcessedStationNumber === station.stationNumber) continue  // already processed this visit, skip
          this.lastProcessedStationNumber = station.stationNumber
          this.remainingDwellTime = station.stationNumber != minStationNumber && station.stationNumber != maxStationNumber ? station.dwellTime : 0
          // calculate the total amount of raw material required by all the stations on the route ahead of this station.
          // const isTerminalForCurrentDirection = (!this.isReturning && station.stationNumber === maxStationNumber) || (this.isReturning && station.stationNumber === minStationNumber)
          // const trainIsReturning = isTerminalForCurrentDirection ? !this.isReturning : this.isReturning
          let totalRawMaterialDemand = 0
          //we are already at a station

          // we first check if there is demand for raw material at this station
          // and if there is stock available in the train then we unload the raw material
          // and charge for it

          const demand = this.rawMaterialDemand.demandAt(station.x, station.y)
          if (demand > 0) {
            const totalUnloading = Math.min(demand, this.rawMaterialOnBoard)
            //earn revenue based on the amount of raw material unloaded and a fixed price per unit of raw material to keep it simple. 
            // We can also add a multiplier based on the distance between the from station and to station to make it more realistic 
            // but for now we will keep it simple with a fixed price per unit of raw material.
            this.financials.incrementRevenueFromRawMaterial(this.getCurrentTimeIndex(), this.trainNumber, totalUnloading * Train.rawMaterialChargePerUnit)
            this.rawMaterialOnBoard -= totalUnloading
            this.rawMaterialDemand.decreaseDemand(station.x, station.y, totalUnloading)
            // console.log(`Train ${this.trainNumber} at station ${station.stationNumber} unloaded ${totalUnloading} units of 
            // raw material, remaining on board: ${this.rawMaterialOnBoard} money earned: ${totalUnloading * Train.rawMaterialChargePerUnit}`)
          }

          for (const nextStation of this.stations) {
            if (!trainIsReturning && (nextStation.stationNumber > station.stationNumber) ||
              trainIsReturning && (nextStation.stationNumber < station.stationNumber)) {
              const demand = this.rawMaterialDemand.demandAt(nextStation.x, nextStation.y)
              totalRawMaterialDemand += demand
            }
          }
          //let us load the train with this raw material if the suppy is available at the station
          let rawMaterialAvailable = this.rawMaterialSupply.availableAt(station.x, station.y)
          let capacity = this.numCoaches * Train.rawMaterialCapacityPerFreightCoach
          let availableCapacity = capacity - (this.rawMaterialOnBoard ?? 0)
          let rawMaterialLoaded = Math.min(totalRawMaterialDemand - this.rawMaterialOnBoard, rawMaterialAvailable, availableCapacity)
          if (rawMaterialLoaded > 0) {
            this.rawMaterialOnBoard += rawMaterialLoaded
            this.rawMaterialSupply.decreaseRawMaterial(station.x, station.y, rawMaterialLoaded)
          }
          let infoText = ''
          if (station.stationNumber != minStationNumber && station.stationNumber != maxStationNumber) {
            infoText = `T${this.trainNumber} F: - ${this.rawMaterialDemand.demandAt(station.x, station.y)} + ${rawMaterialLoaded} = ${this.rawMaterialOnBoard}`
          } else {
            infoText = `T${this.trainNumber} F: ${this.rawMaterialOnBoard}`
          }
          // this.infoText = infoText
          // this.infoTextTicks = 400
          this.popups.addTrain({
            x: station.x,
            y: station.y,
            stationName: station.name,
            trainNumber: this.trainNumber,
            trainInfo: infoText,
          })
          const existingPopupInfo = this.popups.getPopupInfo(station.x, station.y)
          this.displayInfo(existingPopupInfo, station.x, station.y)
        }
      }
    }



    if (!atAStation) this.lastProcessedStationNumber = null  // train has left the station, allow retriggering next visit

    // if (this.infoTextTicks > 0 && this.infoText) {
    //   this.ctx.save()
    //   this.ctx.font = '12px Arial'
    //   // this.ctx.globalAlpha = this.infoTextTicks / 120

    //   const textX = this.x < 10 ? this.x + 10 : this.x - 10
    //   const textY = this.y < 10 ? this.y + 20 : this.y - 10
    //   const metrics = this.ctx.measureText(this.infoText)
    //   const textHeight = 14
    //   const paddingX = 4
    //   const paddingY = 2

    //   this.ctx.fillStyle = 'rgba(0, 0, 0, 0.75)'
    //   this.ctx.fillRect(
    //     textX - paddingX,
    //     textY - textHeight + paddingY,
    //     metrics.width + paddingX * 2,
    //     textHeight + paddingY * 2
    //   )

    //   this.ctx.fillStyle = '#fff'
    //   this.ctx.fillText(this.infoText, textX, textY)
    //   this.ctx.restore()
    //   this.infoTextTicks--
    // }

    this.ctx.save()
    this.ctx.fillStyle = this.color
    this.ctx.translate(x, y)
    this.ctx.rotate(direction)
    this.ctx.translate(-1 * Train.lengthEngine * 0.5, -1 * Train.widthEngine * 0.5)
    this.drawEngine(0, 0)
    this.ctx.restore()

    const occupiedIntersections = new Map()
    this.trackIntersection(occupiedIntersections, x, y)

    const getCoachGap = (coachIndex, spacingScale = 1) => {
      const firstCoachGap = (Train.lengthEngine + Train.lengthCoach + 2 * d) * 0.5
      return firstCoachGap + ((Train.lengthCoach + d) * coachIndex * spacingScale)
    }

    // Keep intersection occupancy based on full simulated train length.
    for (let coachNum = 0; coachNum < this.numCoaches; coachNum++) {
      const gap = getCoachGap(coachNum)
      const { x: x2, y: y2 } = this.getPosition(-1 * gap)
      this.trackIntersection(occupiedIntersections, x2, y2)
    }

    const visibleCoachCount = Math.min(this.numCoaches, this.maxVisualCoaches)
    const simulatedCoachRangeMax = this.hasExplicitVisualCoachCap
      ? Math.max(0, Math.min(this.numCoaches, this.maxVisualCoaches) - 1)
      : Math.max(0, this.numCoaches - 1)
    for (let visualIndex = 0; visualIndex < visibleCoachCount; visualIndex++) {
      const simulatedCoachIndex = visibleCoachCount === 1
        ? 0
        : Math.round((visualIndex / (visibleCoachCount - 1)) * simulatedCoachRangeMax)
      const gap = getCoachGap(simulatedCoachIndex, this.visualLengthScale)
      const { x: x2, y: y2, direction: direction2 } = this.getPosition(-1 * gap)

      this.ctx.save()
      this.ctx.fillStyle = this.color
      this.ctx.translate(x2, y2)
      this.ctx.rotate(direction2)
      this.ctx.translate(-10, -1 * Train.widthCoach * 0.5)
      this.drawCoach()
      if (visualIndex === visibleCoachCount - 1) {
        // draw the number of coaches on the last visible coach
        this.ctx.fillStyle = '#000'
        this.ctx.font = '10px Arial'
        this.ctx.fillText(`${this.numCoaches}`, 2, Train.widthCoach * 0.5 + 4)
      }
      this.ctx.restore()
    }

    this.syncIntersections(occupiedIntersections)
    return { x, y, width: Train.lengthEngine + Train.lengthCoach * this.numCoaches + 5 }
  }

  drawEngine(x, y) {

    let chimneyRadius = Train.widthEngine * Train.chimney_r / 100

    this.ctx.save()
    this.ctx.beginPath()
    this.ctx.rect(x, y, Train.lengthEngine * 3 / 4, Train.widthEngine)
    this.ctx.fill()
    this.ctx.closePath()

    //steam outlet
    this.ctx.beginPath()
    this.ctx.moveTo(x + Train.lengthEngine * 0.5 + chimneyRadius, y + Train.widthEngine * 0.5)
    this.ctx.arc(x + Train.lengthEngine * 0.5 + chimneyRadius, y + Train.widthEngine * 0.5, chimneyRadius, 0, 2 * Math.PI)
    this.ctx.fillStyle = Train.smokeColor
    this.ctx.fill()
    this.ctx.closePath()

    //front portion
    this.ctx.beginPath()
    this.ctx.moveTo(x + Train.lengthEngine * 3 / 4, y)
    this.ctx.quadraticCurveTo(x + Train.lengthEngine, y + Train.widthEngine * 0.5, x + Train.lengthEngine * 3 / 4, y + Train.widthEngine)
    // this.ctx.lineTo(x+Train.lengthEngine*3/4, y+Train.widthEngine)
    this.ctx.fillStyle = this.color
    this.ctx.fill()
    this.ctx.closePath()

    //Coal section
    this.ctx.beginPath()
    this.ctx.rect(x, y, Train.lengthEngine / 4, Train.widthEngine)
    this.ctx.fillStyle = `#000`
    this.ctx.fill()
    this.ctx.closePath()
    this.ctx.restore()

  }

  drawCoach() {

    this.ctx.save()
    this.ctx.beginPath()
    this.ctx.fillStyle = Train.coachColor
    this.ctx.strokeStyle = '#333'
    this.ctx.rect(0, 0, Train.lengthCoach, Train.widthCoach)
    this.ctx.fill()
    this.ctx.stroke()
    this.ctx.closePath()
    this.ctx.restore()

  }
  getPosition(offset) {
    //how far has the Train travelled
    const distance = this.count + offset
    return this.track.getPoseAtDistance(distance, this.isReturning)
  }

  trackIntersection(intersectionsMap, x, y) {
    if (x < this.intersections.offsetX || y < this.intersections.offsetY) return

    const intersection = this.intersections.getCellAtPosition(x, y, Train.intersectionDist)
    if (!intersection) return

    const key = `${intersection.row},${intersection.col}`
    intersectionsMap.set(key, intersection)
  }

  syncIntersections(nextIntersections) {
    let hasNewIntersection = false

    nextIntersections.forEach((intersection, key) => {
      if (!this.activeIntersections.has(key)) {
        this.displayIntersection(intersection.row, intersection.col)
        this.intersections.updateIntersection(intersection.row, intersection.col, this.trainNumber)
        hasNewIntersection = true
      }
    })

    this.activeIntersections.forEach((intersection, key) => {
      if (!nextIntersections.has(key)) {
        this.clearIntersection(intersection.row, intersection.col)
        this.intersections.updateIntersection(intersection.row, intersection.col, null)
      }
    })

    if (hasNewIntersection) {
      // this.beep.play()
    }

    this.activeIntersections = nextIntersections
  }

  displayIntersection(row, col) {
    const { x, y } = this.intersections.getCanvasPoint(row, col)
    this.ctxTemp.fillStyle = 'red'
    this.ctxTemp.beginPath()
    this.ctxTemp.arc(x, y, 5, 0, Math.PI * 2)
    this.ctxTemp.fill()
  }

  clearIntersection(row, col) {
    const { x, y } = this.intersections.getCanvasPoint(row, col)
    this.ctxTemp.clearRect(x - 5, y - 5, 10, 10)
  }

  addStation(station) {
    this.track.addStation(station)
    this.stations = this.track.getStations() // update the stations reference after adding a new station to the track
  }

  getNumStations() {
    //used for calculating the station maintenance/operating cost for this train.
    return this.stations.length
  }

  consumeDistanceTraveledInTimeUnit() {
    const distance = this.distanceTraveledInTimeUnit
    this.distanceTraveledInTimeUnit = 0
    return distance
  }

  adjustmentForDistance(fromToKey) {
    // we can have a simple adjustment factor based on the distance between the from station and to 
    // station to make it more realistic. For example, we can assume that the ticket price increases 
    // by 10% for every 100 units of distance traveled. This is a simplification but it should work for our purposes.
    const [fromStation, toStation] = fromToKey.split('-').map(Number)
    const fromStationObj = this.stations.find(st => st.stationNumber === fromStation)
    const toStationObj = this.stations.find(st => st.stationNumber === toStation)
    const fromCoords = [fromStationObj.x, fromStationObj.y]
    const toCoords = [toStationObj.x, toStationObj.y]
    const distance = Math.sqrt(Math.pow(toCoords[0] - fromCoords[0], 2) + Math.pow(toCoords[1] - fromCoords[1], 2))
    const adjustmentFactor = 1 + (distance / 100) * 0.10
    return adjustmentFactor
  }

  getNumCoachesOrFreightWagons() {
    return this.numCoaches
  }

  extendTrain(positionsForExtendTrain) {
    // We pass these positions to the track to extend it and get the new station location
    const { track, stationLocation } = this.track.extendTrack(positionsForExtendTrain)
    this.track = track
    return stationLocation
  }

  displayInfo(popupInfo, x, y) {
    const canvas = document.querySelector('#canvas')
    const canvasRect = canvas?.getBoundingClientRect()
    const popupLeft = (canvasRect?.left ?? 0) + window.scrollX + x
    const popupTop = (canvasRect?.top ?? 0) + window.scrollY + y + 20

    // check if dynamically created popup info element already exists.
    // if it does not exist then create it.
    let popupElement = document.querySelector(`#popupInfo${x}${y}`)
    if (!popupElement) {
      popupElement = document.createElement('div')
      popupElement.id = `popupInfo${x}${y}`
      popupElement.className = 'popupInfo'
      //create an element to show the station name as the heading of the popup
      const stationNameElement = document.createElement('div')
      stationNameElement.id = `popupInfoStationName${x}${y}`
      stationNameElement.className = 'stationName'
      popupElement.appendChild(stationNameElement)
      //create an element to hold the train info below the station name
      const trainsInfoElement = document.createElement('div')
      trainsInfoElement.id = `popupInfoTrainsInfo${x}${y}`
      trainsInfoElement.className = 'trainsInfo'
      popupElement.appendChild(trainsInfoElement)
      document.body.appendChild(popupElement)
      popupElement.style.top = `${popupTop}px`
      popupElement.style.left = `${popupLeft}px`

      makeDraggable(popupElement)
    }
    //convert the popupInfo object to a string
    //concatenate the station names and that will be the heading of the popup
    
    const stationsNames = popupInfo.Stations.join(', ')
    const stationNameElement = document.querySelector(`#popupInfoStationName${x}${y}`)
    if (stationNameElement) {
      stationNameElement.innerText = stationsNames
    }
    //show the train info below the station names

    const trainsInfoElement = document.querySelector(`#popupInfoTrainsInfo${x}${y}`)
    if (trainsInfoElement) {
      trainsInfoElement.innerHTML   = '' // clear previous train info
     }
    popupInfo.Trains.forEach(train => {
      //each train object has trainNumber and trainInfo
      const trainInfo = train.TrainInfo
      
      const trainInfoElement = document.createElement('div')
      trainInfoElement.className = 'trainInfo'
      trainInfoElement.innerText = trainInfo
      trainsInfoElement.appendChild(trainInfoElement)
    })

  }
}
export {
  Train
}