"use strict";
class Train {
  static lengthEngine = 40
  static widthEngine = 14
  static lengthCoach = 20
  static widthCoach = 12
  static chimney_r = 30
  static smokeColor = `#222`
  static coachColor = `#00ff00`
  static intersectionDist = 10
  static maxNumCoaches = 15
  static minNumCoaches = 2
  static coachPassengerCapacity = 50
  static ticketPrice = 10 // fixed ticket price irrespective of the distance traveled to keep it simple. Revenue is calculated based on the number of passengers on board and the distance traveled.
  
  constructor(ctx, ctxTemp, speed, track, color, numCoaches, trainName, delayBeforeStart, trainNumber, intersections, financials, travelPopulation, getCurrentTimeIndex) {
    this.ctx = ctx
    this.ctxTemp = ctxTemp
    this.track = track
    this.color = color
    // Keep the frame-step divisor >= 1 so modulo logic always advances movement.
    this.speed = Math.max(1, 20 - speed)
    this.numCoaches = numCoaches ? Math.min(Math.max(numCoaches, Train.minNumCoaches), Train.maxNumCoaches) : Math.floor((Train.minNumCoaches + Train.maxNumCoaches) / 2)
    this.ticks = 0
    this.count = 0
    this.isReturning = false
    this.trainName = trainName
    this.trainNumber = trainNumber
    this.paused = false
    this.delayBeforeStart = delayBeforeStart ? delayBeforeStart : 1
    this.intersections = intersections
    this.activeIntersections = new Map()
    this.trainlength = Train.lengthEngine + (Train.lengthCoach + 2) * this.numCoaches
    this.financials = financials
    this.getCurrentTimeIndex = getCurrentTimeIndex
    this.dysfunctional = false
    this.repairTime = 5000 //time in ticks for which the train will be dysfunctional after a collision. This is to simulate the time taken for the train to be repaired after a collision.
    this.repairticks = 0
    // we need stations here to calculate the number of passengers traveling from one station to another station on the route of the train. This is used to calculate the revenue generated by the train operations based on the number of passengers on board and the distance traveled.
    // and also to stop at each station for a certain amount of time.
    this.stations = track.stations
    this.beep = new Audio('./beep.mp3')
    // key is the from station and to station coordinates and value is the number of passengers going on that route. For example, 
    // if there are 10 passengers going from station A to station B, then the key will be "Ax,Ay-Bx,By" and the value will be 10. This is used to calculate the revenue generated by the train operations based on the number of passengers on board and the distance traveled.
    // this is to be populated when the station is added. Let us say that we wanto calculate
    // the number of passengers traveling from station A to station B, 
    // let us say that travelPopulation for A is TA and travelPopulation for B is TB
    // then number is TA*TB/TT where TT is the total travel population.
    // When the train starts at the Starting point it takes in passengers for all the
    // stations on the route. When the train reaches the first station on route, it unloads the
    // passengers for that station and takes on the passengers for all the following stations and so on.
    // In our data model, station is part of the track and hence we will need to access the station information 
    // from the track to get the coordinates of the station and then use that to get the travel population for that 
    // station to calculate the number of passengers traveling from that station to all the following stations on the route. 
    // This is a simplification but it should work for our purposes.
    this.passengerMap = new Map() 
    this.travelPopulation = travelPopulation
  }

  addCoach() {
    if (this.numCoaches < Train.maxNumCoaches) {
      this.numCoaches += 1
      this.trainlength = Train.lengthEngine + (Train.lengthCoach + 2) * this.numCoaches
    }
  }
  removeCoach() {
    if (this.numCoaches > Train.minNumCoaches) {
      this.numCoaches -= 1
      this.trainlength = Train.lengthEngine + (Train.lengthCoach + 2) * this.numCoaches
    }
  }

  setDysfunctional(state) {
    this.dysfunctional = state
    if (state) {
      this.activeIntersections.forEach((intersection, key) => {
        this.clearIntersection(intersection.row, intersection.col)
        this.intersections.updateIntersection(intersection.row, intersection.col, null)
      })
    } else {
      //repair is done, reset the repair ticks and allow the train to move again
      this.repairticks = 0
      //also after the train is repaired
      //set the train to its original position
      this.count = 0
      this.isReturning = false
      this.paused=false 
    }
  }

  startStop() {
    this.paused = !this.paused
  }

  speedUp() {
    this.speed = Math.max(1, this.speed - 1)
  }

  slowDown() {
    this.speed += 1
  }


  draw() {

    // we want to start the train gradually from a zero speed to avoid the jarring effect of the train suddenly appearing at full speed. So we can use the ticks variable to control the speed of the train in the initial phase. The train will start moving after a certain number of ticks have passed, which is determined by the delayBeforeStart variable. We can also use the ticks variable to control the speed of the train in the initial phase. The train will start moving after a certain number of ticks have passed, which is determined by the delayBeforeStart variable. This way we can create a smooth acceleration effect for the train when it starts moving.
    const step1 = 19-Math.floor(this.speed*1/6)
    const step2 = 19-Math.floor(this.speed*2/6)
    const step3 = 19-Math.floor(this.speed*3/6)
    const step4 = 19-Math.floor(this.speed*4/6)
    const step5 = 19-Math.floor(this.speed*5/6)

    const currSpeed = this.ticks < 50 ? step1 : this.ticks < 150 ? step2 : this.ticks < 250 ? step3 : this.ticks < 350 ? step4: this.ticks < 450 ? step5:this.speed

    if (this.dysfunctional) {
      // If the train is dysfunctional, we don't update its position or draw it.
      // till a certain time has passed which is the time needed for th train 
      // to be repaired.
      const healthBar = document.querySelector(`#health${this.trainNumber}`)
      if (this.repairticks % 1000 == 0) {
        //increase the width of the health bar to indicate the progress of the repair
        if (healthBar) {
          const width = (this.repairticks / this.repairTime) * 20
          healthBar.style.width = `${width}px`
        }
      }
      this.repairticks++
      if (this.repairticks >= this.repairTime) {
        this.setDysfunctional(false)
        if (healthBar) {
          healthBar.style.width = `20px`
        }
      }
      return
    }

    //draw is called on each frame from the game loop
    const d = 2 //distance between one coach and the next
    this.ticks++
    //train is not drawn till this.ticks reach a certain level
    if (this.ticks < this.delayBeforeStart * 100) return

    //Also we do not draw the train unless the whole train has reached the starting point. 
    //This is to avoid the train appearing to be cut off at the beginning of the track
    // if (segment && segment.startDistance < this.trainlength) return

    // we have to set the position of the engine based on 
    // how far it has moved on the tracks
    // console.log(this.tick)
    // console.log(`Train ${this.trainName} ticks:${this.ticks} ,globalTicks: ${globalThis.globalTicks}, count:${this.count}`)
    if ((this.ticks % currSpeed == 0) && !this.paused) {
      //this controls the overall speed of the train. The lower the engineSpeed, the faster the train moves. The train moves one step after every engineSpeed number of frames
      this.count += 3
      if (this.track.totalLength > 0 && this.count >= this.track.totalLength) {
        this.count = 0
        this.ticks = 0
        this.isReturning = !this.isReturning
      }
    }

    let { x, y, direction, segment } = this.getPosition(0)

    //distance moved is used to calculate the revenue generated by the train operations. We calculate revenue only for the engine and not for the coaches to keep it simple.
    const distanceMoved = Math.hypot(x - segment.startx, y - segment.starty)
    const currentTimeIndex = this.getCurrentTimeIndex()
    this.financials.incrementRevenueFromOperations(currentTimeIndex, this.trainNumber, this.paused ? 0 : distanceMoved, this.numCoaches)

    // console.log(`Train ${this.trainName} segment:${segment}`)
    this.ctx.save()
    this.ctx.fillStyle = this.color
    this.ctx.translate(x, y)
    this.ctx.rotate(direction)
    this.ctx.translate(-1 * Train.lengthEngine * 0.5, -1 * Train.widthEngine * 0.5)
    this.drawEngine(0, 0)
    this.ctx.restore()

    const occupiedIntersections = new Map()
    this.trackIntersection(occupiedIntersections, x, y)

    //draw a passenger coach
    //distance between center of engine and center of coach is 
    for (let coachNum = 0; coachNum < this.numCoaches; coachNum++) {
      // let gap = Train.lengthEngine + Train.lengthCoach * (coachNum + 1)
      let gap = (Train.lengthEngine + Train.lengthCoach + 2 * d) * 0.5 + ((Train.lengthCoach + d) * (coachNum))
      let { x: x2, y: y2, direction: direction2 } = this.getPosition(-1*gap)

      this.trackIntersection(occupiedIntersections, x2, y2)
      this.ctx.save()
      this.ctx.fillStyle = this.color
      this.ctx.translate(x2, y2)
      this.ctx.rotate(direction2)
      this.ctx.translate(-10, -1 * Train.widthCoach * 0.5)
      this.drawCoach()
      this.ctx.restore()
    }

    this.syncIntersections(occupiedIntersections)
    return { x, y, width: Train.lengthEngine + Train.lengthCoach * this.numCoaches + 5 }
  }
  drawEngine(x, y) {

    let chimneyRadius = Train.widthEngine * Train.chimney_r / 100

    this.ctx.save()
    this.ctx.beginPath()
    this.ctx.rect(x, y, Train.lengthEngine * 3 / 4, Train.widthEngine)
    this.ctx.fill()
    this.ctx.closePath()

    //steam outlet
    this.ctx.beginPath()
    this.ctx.moveTo(x + Train.lengthEngine * 0.5 + chimneyRadius, y + Train.widthEngine * 0.5)
    this.ctx.arc(x + Train.lengthEngine * 0.5 + chimneyRadius, y + Train.widthEngine * 0.5, chimneyRadius, 0, 2 * Math.PI)
    this.ctx.fillStyle = Train.smokeColor
    this.ctx.fill()
    this.ctx.closePath()

    //front portion
    this.ctx.beginPath()
    this.ctx.moveTo(x + Train.lengthEngine * 3 / 4, y)
    this.ctx.quadraticCurveTo(x + Train.lengthEngine, y + Train.widthEngine * 0.5, x + Train.lengthEngine * 3 / 4, y + Train.widthEngine)
    // this.ctx.lineTo(x+Train.lengthEngine*3/4, y+Train.widthEngine)
    this.ctx.fillStyle = this.color
    this.ctx.fill()
    this.ctx.closePath()

    //Coal section
    this.ctx.beginPath()
    this.ctx.rect(x, y, Train.lengthEngine / 4, Train.widthEngine)
    this.ctx.fillStyle = `#000`
    this.ctx.fill()
    this.ctx.closePath()
    this.ctx.restore()

  }

  drawCoach() {

    this.ctx.save()
    this.ctx.beginPath()
    this.ctx.fillStyle = Train.coachColor
    this.ctx.strokeStyle = '#333'
    this.ctx.rect(0, 0, Train.lengthCoach, Train.widthCoach)
    this.ctx.fill()
    this.ctx.stroke()
    this.ctx.closePath()
    this.ctx.restore()

  }
  getPosition(offset) {
    //how far has the Train travelled
    const distance = this.count +offset
    return this.track.getPoseAtDistance(distance, this.isReturning)
  }

  trackIntersection(intersectionsMap, x, y) {
    if (x < this.intersections.offsetX || y < this.intersections.offsetY) return

    const intersection = this.intersections.getCellAtPosition(x, y, Train.intersectionDist)
    if (!intersection) return

    const key = `${intersection.row},${intersection.col}`
    intersectionsMap.set(key, intersection)
  }

  syncIntersections(nextIntersections) {
    let hasNewIntersection = false

    nextIntersections.forEach((intersection, key) => {
      if (!this.activeIntersections.has(key)) {
        this.displayIntersection(intersection.row, intersection.col)
        this.intersections.updateIntersection(intersection.row, intersection.col, this.trainNumber)
        hasNewIntersection = true
      }
    })

    this.activeIntersections.forEach((intersection, key) => {
      if (!nextIntersections.has(key)) {
        this.clearIntersection(intersection.row, intersection.col)
        this.intersections.updateIntersection(intersection.row, intersection.col, null)
      }
    })

    if (hasNewIntersection) {
      // this.beep.play()
    }

    this.activeIntersections = nextIntersections
  }

  displayIntersection(row, col) {
    const { x, y } = this.intersections.getCanvasPoint(row, col)
    this.ctxTemp.fillStyle = 'red'
    this.ctxTemp.beginPath()
    this.ctxTemp.arc(x, y, 5, 0, Math.PI * 2)
    this.ctxTemp.fill()
  }

  clearIntersection(row, col) {
    const { x, y } = this.intersections.getCanvasPoint(row, col)
    this.ctxTemp.clearRect(x - 5, y - 5, 10, 10)
    // this.ctxTemp.clearRect(0,0,1200,800)
  }

}

export {
  Train
}